### ISSUE TITLE
Exception thrown when using Geocoding google

### ISSUE THREAD

**Issue by ludydoo** [chadly/Geocoding.net#85]
Hi,

I receive this exception (sometimes) when sending geocoding requests

System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Easymage.TEC.Entities.Application.QueryHandlers.AddressSearchQueryHandler.Handle(AddressSearchQuery query) in C:\Users\Ludovic\Source\Repos\Easymage.TEC\Easymage.TEC.Entities.Application\QueryHandlers\AddressSearchQueryHandler.cs:line 32

Inner Exception 1:
GoogleGeocodingException: There was an error processing the geocoding request. See Status or InnerException for more information.

**Comment by chadly** [comment]
> See Status or InnerException for more information.

What is the status or inner exception? That is where the error will be.

**Comment by ludydoo** [comment]
There is no inner exception...

**Comment by seanpsherman** [comment]
I get the same error. About every 10 requests but it varies.

**Comment by seanpsherman** [comment]
Mine was a over query limit, throttling it ~10s per request and adding a retry with a longer delay removed this, mostly. Apparently you can still get them regardless using the anonymous api.

**Comment by aatmmr** [comment]
I encountered the same error. However, the `InnerException` was `null` which was helping not at all. 

Getting an API Key solved the issue immediately. A snippet that might help:

```csharp
var geoCoder = new Geocoding.Google.GoogleGeocoder();

geoCoder.ApiKey = "YourAPIKey";

var address =  geoCoder.Geocode( ... )
```

**Comment by alecava58** [comment]
@aatmmr I had the same error. thanks for the tips.

`Geocoding.Google.GoogleGeocoder g = new Geocoding.Google.GoogleGeocoder(geocodingApiKey);` 
` //setting the apiKey in the constructor seems not to be enough` 
` g.ApiKey = geocodingApiKey;`

**Comment by JTRuark** [comment]
I was getting the same issue and tried the suggestions above without success. I made the mistake of using the https string with the key. Using only the key worked.
